language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- export PATH=$HOME/.local/bin:$PATH
- pip install -r requirements.txt
script: make manual
deploy:
  provider: s3
  on:
    all_branches: true
  access_key_id:
    secure: li6AjrLNTc7ToQ0RDnfvuvzR3CUgwoHYyRA5d5v3tNkKgjvvXy1NDWFBNJz5Xzx+tPik6oxgpvOERph+hZ3dzKdE34W9YORHu14h5SWfj8dAvFAluVzS5Jx8dqmJPNvgxWZbfWYbUGBcUHu7okBEfAGJ9+0nuE/U3x7uSZsx3vOC2B7fXiTtrmgp5QJrdYsfGOMliwSC9hAnHkixHJCUcmp5lv/FFmuFDPfZ6yWGXrQV0FvmVDRH6aZlRyAacsJ/3LZ1mQ/RybO1ylTXHM7x3t9+21lAWtBao+DNLMeOMm6ghqeduaRg1SGvo+5W6KMiQeUu1ujCgjaBuiAwA7lMDDrzuqqGpzNFuN5EoT5W6HBfPxgZ0ynbJo49qS68yzkzJLQoTeuZj1tCHaKqKuMVC6VBcjb9uzEtAu1dMIBfG49zdUXKhPnFxSAAyGy2/aioXLeoFufQ9RA1bD5ucarcPEX82nATUg2c8pM+Vl3ZohCucoUrt6X7QGqq5D5SMgsUhganrqXDyfjMjxWJfyovlHOtyRFckvk/y7BvAzjKp+zYIjqI4gmQZxUk9m09pi7prvTHNR1KAzxKPMAI9KeocvG8DKfzivrK/3TqVeDU6kofuYlmTC3xc7gumt46g/mb8JXc7MaV0/uOp1JYtMPyjg7iFPBzdqZzS28Gj2Njyp8=
  secret_access_key:
    secure: napDFKsu7kfhlJZaCoUxWpGCf5wernEW9jT5rOhp0XYB6E6lmHrnSSoJh+kUSMRQBCbDcA2izEHxAjlWKS742ov62zllryvJtDHXDTTMUwB0nbHAjDs03B/5MKIrKtn/fRtEBF4kVYLmj9yYrFV3doOk+VYaBoABWccIp7ty5Ors3dCuJlX0KjSaWQ0naxVIN6zcYjfHywmsrn0q2z/EfCA7HMUuD6QLwe5peVc8H4wmpFLLYVm2tj88irvkbWTiiSQ7iXWd2yd63SF2T6zg5GdC610zhC+f/L5u0n6PdlUVoC5TTNU2OwPdQ84Ozaun/cUHpMzeGsgyBP5blsc4jLalTHRv9LZKzpdlfIHCNLI12DRJqLq7W9lJeOBChQ6ZnREYcMZPwFdvn8+xTNaffiv5lqIQo3kWtNQ3sL8JhZeGUdUG70XZKl/H4DXxYNm9Ow666qIiUA6MU6jz6Ftc9XpzlFy239y2Kvy7lyWT5d8aD4uI4lBqzx9VTO8/9G2tY9v1PvJXOz348GsYoPmL+qqj6cO782CAoJ9cpXpb+uCdLP4cRZ1fVHjV6CdPCpGpn9WNKluWKlW0OF23mbcKIE/fFabWMXenznhBoT8vstqM/LX5D6x2N0xv+KFhcJ3dq9kEWZmmRZP9oCjh8mPLbRTFHL7AQc7OudtVStGrXzU=
  bucket:
    secure: WYCQTyJplfXsheygbSVbpnHDQ86t1/7plrBfbJ+WaOUV+wNXA7fcqWZsRKh8uD/XVEpSPw9X6mbL2wPltSqW3f26owl7kieVzQo9YwHgllMC+cqW+xDmrUJfQugMwGl7mCMI2YHVloeCRdIvxT0NK+07ntl5w88O/ZVkEUI1smz/yGojXM6cLwC3wx0+zNEM0xaCRVxYOh7ZZC7KT+EMUTmZzW8L5ZX6qMPqUvgVd8UEe5J8Yc+KzmqNP8jOPhXP/IkWwJF7NE52xkXR96FmI5ptgw6xJJ3fiHISxuC1eZVQQUYzzYyb8Qus5e6su/O1JPLYVFUyc4p2uToS8zi8mcgvkbtk11Pl4QHai1ipYAxV93Ypj1ufv6RjygrL7ja3aI93zbLKsGYXovESz5Qquiczsc05gg4I1nX7/xI133dLuuk1g3y6z0T8IwqCnGwtpkxUq3Y7cRrTT0wvVjiIoqrX+eehw0Fcc8BpQc+HGjSF50dnyCMOUGXN5omAE/lSDI82S/VxS8tmznZ26z+ZjYP5vhzPzUrW3APD/hWBRqDs9t4zEXns2hXYQahDgUSKFMzrvR464F7auRV4QvA3vzWAMG32xPLHbNdUhJ3rvz3KDcgdOLL+SautvmbRIOHApkkjQuFBGrdemud7R5viwFAub+4DY21/38FeMRPIF7w=
  upload_dir: lambdas
  server_side_encryption: true
  local_dir: build
  region: us-west-2
  skip_cleanup: true
notifications:
  slack:
    secure: DGhjxMg7qbQ8blBvaNTxZjW2aXmA1BFJVirAXiLz/zVIqBOoYWEynCBPGeuCpT/2vMytdWJMgvLyiWTme87ao8x4mFO0t5Z3yR6e/7YzUJ6oAEx7z+Nuu2PaP3o1yIuoaa0TIbvGw0rlWQ5MLmK/zrSEaIv7HySa0yllMkc15cAtw0HARHUST1eTQIhqz/Z8QfW0O0aCjyZ453ECvQ86MQBZb5jaxwZsVqWaNLRavk6V2mSFS/xJoI1mn0OCr3teNg41jKLj8JsMyMoALS1/aHAhTMOAQOraFiolxROmZcJl0pbIi+8/Gt1aURNooj9wLh2+gAtmQfLlEpUH0CUY+5dQJtXk1bN3+6ui6UmlX21W2tRQI2h2I/7oAngLuc5GPdoAs2KClC+7S0cozpXCrQJp08IqTtvCQSuPHF/E863oCReiGlZ9YY1JoSNL3lN5xXgZpas2OE3oSRN88ZqutoWfcSd0tBd8kb7ard0XOnX+TXzEscQrZ/Xkes0Ei1ZhX+qi2uQJS0oNva5ei1KCby+8r/iQhwQT4/ad2AFz5ak7qRxY86xmyiChsgx5RA7H8M2NiBlljIHI4q4qDYolCiY4UqgacMH7TtptoP/3JFacoXDUU98SgwGV6vTue7yPibmoS7+rwc5p/cE1obVKYV9xvFc8Q1h475J92k+ObhI=
