language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- export PATH=$HOME/.local/bin:$PATH
- pip install -r requirements.txt
script: make manual
deploy:
  provider: s3
  on:
    all_branches: true
  access_key_id:
    secure: "cAf6fD6HEksS8AyKINz5NFSF9k5AftiYslZC/RU0jcj3lzgRy9w7Tfevk3j1NVNKc2K72fw4pHvIt8RriVcXmMfW85kM0Po3IdDeA57aetoSMCuHHHqwDArzDKkg+t1LdIA8rOGG2sTNhsCASDHrPhB23uCPAIp3RvHwdoJmvIlkrNW4GSzDtJjASz2WjYclPBWLbDAWCGmxsPCDuvmofQKJ1Aub6t6PeATg4RoxjShy1KdruJbkT77HZmzDQ6iUf6NGoX0I7kW6Z/uoXq2/3m2tMe8iWsKA4LxJ2PeeiIirzQ+SZIVp+GvRz6jpQZIV7K9hAej8tnDwt+KWmKEjKtW3UnoQYGKtm5C420+qtLmTeIcd6JqQZTlm0EaffF+ouVnA/5wewIJ0CWwWsRI6IeaMRd0VF02flbcv476Zq1JykqYtpCf+Gr2UCbvm/+4dcR0pZRnqdKKZA09SGFYtwA1avZnrWaRPE2mxeD776sMQs53bqCsEs0/O3X7pf0j6/0Jvf+Oy2j1AUR2K/7bwCdreFQ5Rp5qGZ6AZeQMvqdeCN5rwXAyFT4PZSDWKEC+fLL6Bu6kY9nMViY9bd4aGXELdrUHrrNqOOeQZnBRaO5TX/DmiTL2/zXtPuKwSg2EljBIHDhjsYp9TZfqGxIItRQxcXjE8cjbG6k/YalfVEWw="
  secret_access_key:
    secure: "fAWKNTaK9Lzd5Pqnz6vckaFPHGBA7qT4Oh3bl9AToUy3OJslqdoL0S/kbgAeZKfyZfyApTuzPuuyR23qH8qQspWwWcdEXqmM1AmhyVZYrQAemxYMVjVSNzsbxivvT1L5Jj4FrUdf9j21zrcDqKwAAf9N84EOf9qLlm90TcAUZ6Ub/iuW/af6DbH7Ds+r3um2Rk7Va5qDv7QavvrscaC7nVtRjUvZhLQCHZKxgrBzY9qkHY5l/+ot7mJJQxkvUbbmu/ZWOACs/mPzNwk6XCXFoXKt3T8vwgvcoC+yteotEPeFI2SPGr+bs55UAXYohGtoUCsOAPl8+4chfzXzs5czkz8JnEL/jI2vu6DnSCPvXL+xMjbZ1OYe3r7Rll/xxWANnYumNys4dlD1uhjpgW7qt/Cd2z0BUGiwAMA4jTSN+X8O/gNLd7mL5Q5ygqAi+SyfrowdW7VsNev4qD6d1MG27fYvhG7iYKWq+9M4iL9NTVA+fDdAPd8tAWXzvEEK+JofohSwE39oIReHiBiTJ3QT5cDzjxpaBX+eTyqOJ6mOEEffvYPQNodngutmDKAonYCZ/BHDoJOWjJXcGlw7ZPHb5w/p/y7LdazGQ8QD591v0r7EiM79m3xjh9RtVt4LSX1j1T2l3S5MiIzGhIe8F5k3XBTZYvikXRikUobHs7Ckkr8="
  bucket:
    secure: "Y5BMOEGiGj9SFLeRbYe4MhPbCoDtM7kLKEttlsonbLIo6HpRtCdL8DHFPbl6Va/RDXeTVhHFDbEhVsYFNChdvpxm1l5nBBeZ63nA+cHQg/EjQMVWazN9Hhbba2McMEXsyuDNhePlt0JUoi5S5IkthDhGHRcpAWKODCxQ12+do37C56zhxWdsxnEju/HN2Jes81Cjg/VL14Tg+TWcKPUPNKjWa9NmHXLPzIfeC2vr6MCgAerwgDNMovUzRMK3roHjmmyBw7E+isPvWMDL2hnpGYK7Tf71fvpIcjxywSMkT7C5Amryj8mdffjwS+/PCwUow2q3HA6OxmJcvGQOFhPUJmFFsbbUV4+S4TmngTpEut7chzcd8+hq7gzhOpaczW2+jAZkaHknSimmRvwDFZ0ZWYf/+0pfKOiHxI6qxy5mFP1i0+sHhHw4kBTGRORJrmUwV89nK9xMGklc/iixCLBCSHMNF5DpZQFR0Dkhjrgscmo4os4aN1OEu/3ejou2rNRzP0N/YypNPaDfWj14WrpzoYa3MApF7Vjrn8xg1iw4NrOgD1d17ui/MTkKSEojmvmDz2txpOpMmes0zxJmGMc5WjvZN2b1CJEz8AHlA7sqpG++t210W3GFVgyN3bMjReyHsOOhRurIpCMI+vrE9HfR3kuObiMZsP7MbOjMVn2EdqU="
  upload_dir: lambdas
  server_side_encryption: true
  local_dir: build
  region: us-west-2
  skip_cleanup: true
notifications:
  slack:
    secure: "SicLR8hveagCAw9XsyLlLxDgjL3KyWR0T0rPZRhG3ttNbbw+dRpSfnKtpaMBkljtRj9/LTp7f03dEZg0lNrgctUXkNI5Fqd4+8UFh+uT1u2VqT+krJhoBZjECXJKUTve7D9ggpcC6UXW6hDb85qIY3kUhTNtUOZZ8uO6PxtbEPttfoPEbCGvpmlMrRJq8AOsp4C8dkqXseVd/nAHybazTM241y+zzpI6eyj79xkE5StiWWJ0EcWaNfYjvD+TqS7XZ0kGRGRVujmbPuNJhg/nBk6QvcRlLCMwv4in2xPEpWLeqTF4wNZgBmI9rMppbzB4BzxL2n/v5RN5PAH5aT4l0uegMn1HxP3Pc0Led7dDcN4OtlzyWCrvHGEZoslyGLXjp30BErpCtM8EV3FMgjbFuGZqZ6Hgiqrpk9x3+nannxkUZgi3e8IpysK4sW1eLq3yVaLAIKCvTWvd18QOAP01Y29NkbXzh4kafqgz3jRuSggGfGSdsSL/iFUUx2BCC4v4QufqkrgHhi37UOUDwGeHn9UayYgoiLonZ+4YpMQnNDQI4S7l8ONI8r9zdHx9P6GmtUW3FxRbHu7InzKaKT4Q5hpGNi6WnRFvBn61J1YuZ/+9Uu90pPsR+6EhSkcnElQ36Do5kua+FMJfEX52g/ie/Y1PnDuzBSLB28dcaDYGdh4="
