name: Lambda deployment

on:
  push:
    branches: 
      - main
      - master
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install --target ./package -r requirements.txt; fi
    - name: Create ZIP
      run: |
        (cd package;zip -r spotify-history.zip ./*)
        zip -gj package/spotify-history.zip functions/spotify-history/*.py
        mv package/spotify-history.zip .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: ${{ secrets.AWS_SESSION_NAME }}
        aws-region: us-west-2
    - name: Copy deployment ZIP to AWS
      run: |
        aws s3 cp spotify-history.zip s3://${{ secrets.DEPLOY_BUCKET }}/${{ secrets.DEPLOY_PATH }}

