name: Lambda deployment

on:
  push:
    branches: 
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create ZIP
      run: |
        (cd package;zip -r spotify-history.zip ./*)
        zip -gj package/spotify-history.zip functions/spotify-history/*.py
        mv package/spotify-history.zip .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Copy deployment ZIP to AWS
      run: |
        aws s3 cp spotify-history.zip s3://${{ secrets.DEPLOY_BUCKET }}/${{ secrets.DEPLOY_PATH }}
    - name: Send message to Slack API
      uses: archive/github-actions-slack@v1.1.0
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: test
        slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓
    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
